export * from "./ClassByIdDefs";
export * from "./ClassCreatorDefs";
export * from "./ClassDeleterDefs";
export * from "./ClassRenamerDefs";
export * from "./ClassTypeDefs";
export * from "./ClassUpdaterDefs";
export * from "./ClassDashboardDefs";
export * from "./SampleClassesDefs";
export * from "./UserClassesDefs";
